name: Python Code Quality
on: [push]
jobs:
  code_quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup uv
        uses: ./.github/actions/setup-uv

      - name: pre-commit code quality checks
        run: uvx pre-commit run
  
  pytest:
    runs-on: ubuntu-latest
    needs: [code_quality]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-uv
      - run: uvx --with pytest-cov pytest -v --durations=0 --cov --cov-report=xml
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}