name: Test Python Code Workflow

on:
  push:
    branches:
      - main

jobs:
  code-quality-checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      # Install project dependencies needed for code quality checks
      - name: Install code quality checks
        uses: michaelellis003/python-package-custom-actions/setup-uv@v2
        with:
          python-version: ${{ matrix.python-version }}
          dependency-group: 'code-checks'
          
      - name: Run pre-commit
        run: uv run pre-commit run --all-files