name: Python Code Quality
on: [push]
jobs:
  code_quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: install uv
       run: |
         curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: pre-commit code quality checks
        run: uvx pre-commit run