name: Python Code Quality
on: [push]
jobs:
  code_quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup uv
        uses: ./.github/actions/setup

      - name: pre-commit code quality checks
        uses: pre-commit/action@v3.0.1