name: Python Code Unit Tests
on:
    workflow_run:
      workflows: ["code-quality"]
      branches: [main]
      types: 
        - completed
jobs:
  pytest:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
        - run: echo 'code-quality workflow passed'