name: Release
permissions:
 contents: write  # For tag/push operations

on:
  # This triggers whenever the "CI" workflow completes
  workflow_run:
    workflows: ["CI"]      # Must match the name: "CI"
    types: [ "completed" ]

jobs:
  release:
    runs-on: ubuntu-latest
    # Only proceed if the CI workflow ended in success
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
        - name: Checkout code
          uses: actions/checkout@v4
    
        - name: Setup uv
          uses: ./.github/actions/setup-uv

        - name: get version
          run: |
            VERSION=$(uvx --from=toml-cli toml get project.version --toml-path pyproject.toml)
            echo "VERSION=$VERSION" >> $GITHUB_ENV
        
        - name: show version  
          run: echo "Retrieved version $VERSION from pyproject.toml"
          env:
            VERSION: ${{ env.VERSION }}

        - name: Create and push tag
          run: |
            git tag "v${VERSION}"
            git push origin "v${VERSION}"
          env:
            VERSION: ${{ env.VERSION }}
          
        - name: Update major version tag
          run: |
            MAJOR=$(echo "$VERSION" | cut -d. -f1)
            git tag -fa "v${MAJOR}" -m "Update v${MAJOR} tag to v${VERSION}"
            git push --force origin "v${MAJOR}"
          env:
            VERSION: ${{ env.VERSION }}